### PR TITLE
Jt Add Panel config setup

### PR DESCRIPTION
**Pull request by jonnitg**
Moved the #1 logic and clean it and refactor the code

### CODE REVIEW

**Comment by bszyk** [comment]
@jonnitg Some differences from when I tested #1 :
- Screen Visibility doesn't seem to work for me now
- Logged in/logged out still works
- The Admin setting for User Roles was working for me, but not when I tested it with a logged-in Subscriber account

**Comment by bszyk** [comment]
Converted to use `<BoxControl>` for the UI -- looks to be adding to the variables in the style att as expected (although not rendering the style).

Screen Shot 2021-07-21 at 12 17 45 PM
Screen Shot 2021-07-21 at 12 18 24 PM

**Comment by jonnitg** [comment]
> Converted to use <BoxControl> for the UI -- looks to be adding to the variables in the style att as expected (although not rendering the style).

The reason is due the [CSS Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) it is working but the WP default styles are overriding it, if we do inline styles it will work

**Comment by bszyk** [comment]
Screen Shot 2021-07-23 at 2 13 59 PM

**Comment by bszyk** [comment]
Added a parent toggle to device visibility.

Default view:
Screen Shot 2021-07-23 at 6 07 02 PM
---
Some options selected:
Screen Shot 2021-07-23 at 6 06 55 PM
---
All options selected:
Screen Shot 2021-07-23 at 6 07 14 PM

**Comment by easilyamused** [comment]
Hi Team,

I assumed the user could toggle the section open or closed to view the 3 settings and then the user could hide them. The action of toggling Hide on X would be good enough. Not sure we need the main on or off toggle.

**Comment by bszyk** [comment]
@easilyamused I can understand that - mostly went that route initially to clean up the panel, got me to divide into two sections: Device Visibility and User Visibility. 

Both turned off:
Screen Shot 2021-07-27 at 11 05 58 AM

User Visibility toggled on:
Screen Shot 2021-07-27 at 11 06 11 AM

User Role checkboxes:
Screen Shot 2021-07-27 at 11 06 26 AM

**Pull request merged**
