### PR TITLE
Jt alignment panel

### PR DESCRIPTION
**Pull request by jonnitg**
Added settings for Flex - Container
Screen Shot 2021-07-15 at 10 23 30 AM

Added settings for Flex - Item
Screen Shot 2021-07-15 at 10 23 51 AM

### CODE REVIEW

**Comment by bszyk** [comment]
@jonnitg I couldn't get any of these features to work. I tested with a Columns block with three inner Column blocks (see screenshot) - side panel shows trying to set the Columns block to `flex-direction: column`. Was there a block that worked for you?

Screen Shot 2021-07-20 at 6 12 31 PM

**Comment by easilyamused** [comment]
I think everything is a great start, but maybe we backlog this one. 
It might be too advanced to make sure it's fully working in the next 3 days.

If anything would love to get basic floats working and come back to this. 

I want to set a max-width on something and also have the ability to left or right align.

**Comment by bszyk** [comment]
@easilyamused agreed on backlogging this.

**Comment by surajkrsingh** [comment]
Reviewed this PR and found a few issues
1. Few options don't work
2. UI doesn't look user intuitive
3. Need deep testing with each option

**Comment by surajkrsingh** [comment]
Progress on flex alignment feature
1. Refactored some code from the old commit
2. Fixed flex container options
3. Improved the options UI
5. Added gap option to set the gutter/gap between flex items.

image

**Comment by surajkrsingh** [comment]
@royboy789 
Please review this PR.

**Review by royboy789 — APPROVED** [review]

**Pull request merged**
