### PR TITLE
Jt - Add custom css panel

### PR DESCRIPTION
**Pull request by jonnitg**
Asana ticket: https://app.asana.com/0/1200406005191183/1200395066725966

- Demo
Screen Shot 2021-06-24 at 6 25 22 PM

- Panel
Screen Shot 2021-06-24 at 6 24 10 PM

### TODO

- Instead of Inline styles, should contain css classes.
- Replace the textarea for the Code editor.

### CODE REVIEW

**Comment by bszyk** [comment]
Hey @jonnitg, I ran into some issues with this - attached screenshot shows the css text editor rendering a little weird (doesn't end like yours or show 'Double check your code'). Also, the CSS only worked on the frontend for me when I selected the element in the CSS itself, it didn't update in the editor like your screenshot shows.

Screen Shot 2021-07-20 at 7 47 00 PM

**Comment by easilyamused** [comment]
There are 2 approaches here, the inlines  styles that get added to the element that you are editing,

or 

We use selectors like Elementor.  This would also let a user target a nested item without writing CSS at the nested level. 

Example:

selector {}

selector h2 {}

I like the flexibility of the 2nd option more.

**Comment by surajkrsingh** [comment]
I have a question about this feature.
1. Adding a block-level option should only be for that block only ( then why are we taking selector, here just need attribute and values like `background-color: red;`

Here can we add it as inline style or
Can wrap all custom CSS attribute in a class and just need to push the class on that element using only

2. If we want to make it a global option then we have to implement it in different and it should only appear on any block-level ( mean not bounded it the block selection) and there will be a single custom CSS editor for the entire page/post

As per current PR - It is on block level but it embedded the custom CSS in the head as global which affects another element too.

@royboy789 @easilyamused 
 I need a specific way to move in that direction, 
 please suggest the way as per user preference and your decision

**Comment by surajkrsingh** [comment]
**After testing this PR, I found three bugs with custom CSS.**
1. CSS editor doesn't active the customer when clicked on it.
2. Added CSS doesn't reflect on the admin editor page but work on the frontend.
3.  Changing the block doesn't update the CSS on the CSS editor box

**Comment by surajkrsingh** [comment]
Preview 
image

**Comment by surajkrsingh** [comment]
@royboy789 Please review the PR.

**Review by royboy789 — APPROVED** [review]

**Pull request merged**
