### PR TITLE
Jt - Add dimensions panel

### PR DESCRIPTION
**Pull request by jonnitg**
Asana Tickets:
 - https://app.asana.com/0/1200406005191183/1200261278131985
 - https://app.asana.com/0/1200406005191183/1200261278131987

- Settings
Screen Shot 2021-06-24 at 6 29 05 PM

- Demo
Screen Shot 2021-06-24 at 6 30 10 PM

### TODO

- [x] Add min/Max for width and height

### CODE REVIEW

**Comment by bszyk** [comment]
@jonnitg Everything seems to be working really well except for `max-width`.

**Comment by easilyamused** [comment]
Can we get screenshots of the min-max settings too, please?

**Comment by bszyk** [comment]
@easilyamused This is the dimensions panel as it currently is.

Screen Shot 2021-07-27 at 10 56 58 AM

**Comment by jonnitg** [comment]
The Max-width is working fine, the issue is the default CSS of WP that overrides the max-width...
https://user-images.githubusercontent.com/10889984/129051211-aca8baeb-09a1-41fb-b2e5-7ed439060fc6.mov

Should I add the `!important` property?

**Comment by surajkrsingh** [comment]
Previewed this PR and initially found a few issues.
1. Few options doesn't reflect on the editor
image

2. Contents overflowing the box dimension 
image

**Comment by surajkrsingh** [comment]
As per discussion in the meeting.
We will add the one more option to control the **overflow contents** when setting any height.

**Comment by surajkrsingh** [comment]
Added new option to control the contents overflow-
Screenshot 2021-11-20 at 8 57 51 PM

**Comment by surajkrsingh** [comment]
@royboy789 
Please review this PR.

**Review by royboy789 — APPROVED** [review]

**Pull request merged**
